### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by ghost** [l3mpik/feedbot#1]
JOKING... ACTUALLY REALLY NOT WORKING. I LOVE THE PROXY GENERATOR AND CHECKER BUT NOT WORKING EXACTLY
[http://puu.sh/vBwrM.png](url)

ALSO YOUR SLITHER FEEDER BOT IS ATTACHED COUNT 0, IT SAYS WAITING FOR CLIENT ONLY REST IS WORKING PERFECTLY, NO ERRORS. I CHECK ALL PORT INPUTS, EVERYTHING OKAY BUT IT STUCK BOT COUNT 000000000000.

OH SORRY, HOW CAN I DISABLE CAPS LOCK?

**Comment by freaky767** [comment]
wat the fack
